### ISSUE TITLE
Can't click on header links from child pages

### ISSUE THREAD

**Issue by bigandy** [speedtracker/speedtracker.org#6]
https://speedtracker.org/connect I cannot click on the menu items because the SVG is on top.

also affects /blog, /encrypt, and blog posts

I am on Windows7 and have tried Chrome and IE11

**Comment by eduardoboucas** [comment]
Ouch! This was caused by recent changes to the site. I'll fix this ASAP. Thanks!

**Comment by eduardoboucas** [comment]
Can you check now, please?

**Comment by bigandy** [comment]
Yes, working perfectly. Thanks!
